export const BLOG_SLUG_MAP = {
  ru: {
    // Core product/service articles
    'kak-vybrat-korporativnyj-podarok': 'korporativ-sovgani-qanday-tanlash',
    'lazernaya-gravirovka-podarkov': 'lazer-gravirovka-sovgalar',
    'podarochnye-nabory-s-logotipom': 'logotipli-sovga-toplami',
    'brendirovanie-suvenirov': 'suvenir-brendlash',
    'top-idei-podarkov-na-novyj-god': 'yangi-yil-sovga-goyalari',
    'ekonomiya-na-korporativnyh-suvenirax': 'suvenir-byudjetini-tejash',
    'podarki-na-navruz': 'navruz-sovgalari',
    'korporativnye-podarki-s-logotipom-polnyy-gayd': 'korporativ-sovgalar-logotip-bilan-to-liq-qollanma',
    'korporativnye-podarki-s-gravirovkoy-metody': 'korporativ-sovgalar-gravyurasi-usullari',
    // Fixed: was pointing to non-existent 'lazer-gravyurasi-texnologiyasi'
    'lazernaya-gravirovka-podarkov-tehnologiya': 'lazer-gravirovka-sovgalar-tehnologiyasi',
    'merch-dlya-kompanii-brendirovanie': 'kompaniya-merchi-brendlash',
    'brendirovannye-zazhigalki-i-chasy-s-logotipom': 'logotipli-zajigalka-va-soat',
    'korporativnye-podarochnye-nabory': 'korporativ-sovga-toplamlari',
    'korporativnye-podarki-na-navruz': 'navruz-uchun-korporativ-sovgalar',
    'welcome-pack-novym-sotrudnikam': 'yangi-xodimlar-uchun-welcome-pack',
    'kak-podgotovit-maket-logotipa': 'logotip-maketi-tayyorlash',
    'podarki-dlya-bankov-i-finteha-tashkent': 'banklar-va-fintex-uchun-sovgalar-toshkent',
    'chasy-s-logotipom-korporativnye-podarki-tashkent': 'logotipli-soat-korporativ-sovgalar-toshkent',
    'podarki-na-korporativnye-sobytiya-tashkent': 'korporativ-tadbirlar-uchun-sovgalar-toshkent',
    'podarki-dlya-horeca-i-restoranov-tashkent': 'horeca-va-restoranlar-uchun-sovgalar-toshkent',
    'kak-vybrat-podarki-dlya-sotrudnikov': 'xodimlar-uchun-sovga-tanlash-chek-list',
    'gravirovka-na-biznes-podarkah': 'biznes-sovgalarda-gravyura',
    'korporativniy-merch-kak-instrument-marketinga': 'korporativ-merch-marketing-vositasi',
    'byudzhet-na-korporativnye-podarki': 'korporativ-sovgalar-byudjeti',
    'srochniy-zakaz-korporativnyh-podarkov': 'shoshilinch-korporativ-sovga-buyurtmasi',
    'eko-podarki-dlya-biznesa': 'biznes-uchun-eko-sovgalar',
    'keys-brendirovannye-podarki-dlya-it': 'keys-brendlangan-sovgalar-it-kompaniya',
    'loyalnost-sotrudnikov-korporativnye-podarki': 'xodimlar-sadoqati-korporativ-sovgalar',
    'kak-vybrat-korporativnyj-podarok-b2b': 'b2b-korporativ-sovga-tanlash',
    'personalizatsiya-novyy-standart-gravirovka': 'shaxsiylashtirish-yangi-standart-gravyura',
    'process-zakaza-korporativnyh-podarkov': 'korporativ-sovga-buyurtma-jarayoni',
    'keys-welcome-pak-it-kompaniya-tashkent': 'keys-welcome-pak-it-kompaniya-toshkent',
    'godovoy-plan-korporativnyh-prazdnikov': 'korporativ-bayramlar-yillik-rejasi',
    'gastronomicheskie-nabory-na-navruz-tashkent': 'gastronomic-toplamlar-navruzga-toshkent',
    'kak-vybrat-vip-podarok-partneru-uzbekistan': 'vip-hamkor-uchun-sovgani-qanday-tanlash-ozbekiston',
    'welcome-pack-dlya-it-kompanii-tashkent': 'it-kompaniya-uchun-welcome-pack-toshkent',
    'lazernaya-gravirovka-protiv-uf-pechati-chto-vybrat': 'lazerli-oyma-va-uf-pechat-nimani-tanlash',
    // 8-march series
    'podarki-na-8-marta-sotrudnicam': '8-mart-uchun-korporativ-sovgalar-goyalari',
    'originalnye-podarki-na-8-marta': 'originalnye-podarki-na-8-marta-uz',
    'korporativnye-podarki-na-8-marta-v-tashkente': 'korporativnye-podarki-na-8-marta-v-tashkente-uz',
    'chto-podarit-mame-na-8-marta': 'chto-podarit-mame-na-8-marta-uz',
    'chto-podarit-kollege-na-8-marta': 'chto-podarit-kollege-na-8-marta-uz',
    'chto-podarit-rukovoditelyu-na-8-marta': 'rahbar-uchun-8-mart-vip-goya',
    'chto-podarit-devushke-na-8-marta': 'chto-podarit-devushke-na-8-marta-uz',
    'chto-podarit-na-8-marta-devushke-mame-kollege': 'chto-podarit-na-8-marta-devushke-mame-kollege-uz',
    'nedorogie-podarki-na-8-marta': 'nedorogie-podarki-na-8-marta-uz',
    'gravirovka-v-tashkente-na-8-marta': 'gravirovka-v-tashkente-na-8-marta-uz',
    // B2B / content cluster (updated mappings — now point to newer UZ counterparts)
    'polniy-gid-po-korporativnym-podarkam': 'korporativ-sovgalar-toliq-gid-2025-uzbekistan',
    'welcome-pack-dlya-sotrudnikov': 'welcome-pack-hr-uchun-toliq-gid',
    'merch-dlya-it-kompaniy-tashkent': 'it-kompaniya-uchun-welcome-pack-chek-listi',
    'podarki-sotrudnikam-hr-gayd': 'xodimlarga-sovga-loyalikni-oshirish',
    'podarki-klientam-partneram-vip': 'b2b-hamkorlar-uchun-sovgalar-etiket-gid',
    'chek-list-zakupshchika-podarkov': 'korporativ-sovgalar-zakupshchik-chek-listi',
    'idei-vip-podarkov': 'biznes-hamkorlar-uchun-vip-sovgalar',
    'delovoy-etiket-biznes-podarki-uzbekistan': 'uzbekistonda-biznes-sovga-etiketi',
    'keys-welcome-pack-povysil-enps-v-it-kompanii': 'keys-welcome-pack-povysil-enps-v-it-kompanii-uz',
    // New true-counterpart pairs added in hardening pass
    'case-study-welcome-pack-enps': 'keys-brendlangan-sovgalar-it-kompaniya',
    'korporativnye-podarki-b2b-etiket': 'b2b-korporativ-sovga-tanlash',
    'podarki-sotrudnikam-loyalnost': 'xodimlar-sadoqati-korporativ-sovgalar',
  },
  uz: {
    'korporativ-sovgalar-boyicha-toliq-qollanma': 'polniy-gid-po-korporativnym-podarkam',
    'korporativ-sovgani-qanday-tanlash': 'kak-vybrat-korporativnyj-podarok',
    'lazer-gravirovka-sovgalar': 'lazernaya-gravirovka-podarkov',
    'logotipli-sovga-toplami': 'podarochnye-nabory-s-logotipom',
    'suvenir-brendlash': 'brendirovanie-suvenirov',
    // xaridor-chek-listi-b2b still maps to same RU article (older UZ counterpart)
    'xaridor-chek-listi-b2b': 'chek-list-zakupshchika-podarkov',
    'yangi-yil-sovga-goyalari': 'top-idei-podarkov-na-novyj-god',
    'suvenir-byudjetini-tejash': 'ekonomiya-na-korporativnyh-suvenirax',
    'navruz-sovgalari': 'podarki-na-navruz',
    'korporativ-sovgalar-logotip-bilan-to-liq-qollanma': 'korporativnye-podarki-s-logotipom-polnyy-gayd',
    'korporativ-sovgalar-gravyurasi-usullari': 'korporativnye-podarki-s-gravirovkoy-metody',
    // Fixed: was non-existent 'lazer-gravyurasi-texnologiyasi', now correct slug
    'lazer-gravirovka-sovgalar-tehnologiyasi': 'lazernaya-gravirovka-podarkov-tehnologiya',
    'kompaniya-merchi-brendlash': 'merch-dlya-kompanii-brendirovanie',
    'xodimlar-uchun-sovgalar-hr-qollanma': 'podarki-sotrudnikam-hr-gayd',
    'mijoz-hamkorlar-uchun-sovgalar-vip': 'podarki-klientam-partneram-vip',
    'logotipli-zajigalka-va-soat': 'brendirovannye-zazhigalki-i-chasy-s-logotipom',
    'korporativ-sovga-toplamlari': 'korporativnye-podarochnye-nabory',
    'navruz-uchun-korporativ-sovgalar': 'korporativnye-podarki-na-navruz',
    'yangi-xodimlar-uchun-welcome-pack': 'welcome-pack-novym-sotrudnikam',
    'logotip-maketi-tayyorlash': 'kak-podgotovit-maket-logotipa',
    'welcome-pack-yangi-xodimlar': 'welcome-pack-dlya-sotrudnikov',
    'it-kompaniyalar-uchun-merch-toshkent': 'merch-dlya-it-kompaniy-tashkent',
    'banklar-va-fintex-uchun-sovgalar-toshkent': 'podarki-dlya-bankov-i-finteha-tashkent',
    'logotipli-soat-korporativ-sovgalar-toshkent': 'chasy-s-logotipom-korporativnye-podarki-tashkent',
    'korporativ-tadbirlar-uchun-sovgalar-toshkent': 'podarki-na-korporativnye-sobytiya-tashkent',
    'horeca-va-restoranlar-uchun-sovgalar-toshkent': 'podarki-dlya-horeca-i-restoranov-tashkent',
    'gastronomic-toplamlar-navruzga-toshkent': 'gastronomicheskie-nabory-na-navruz-tashkent',
    'vip-hamkor-uchun-sovgani-qanday-tanlash-ozbekiston': 'kak-vybrat-vip-podarok-partneru-uzbekistan',
    'it-kompaniya-uchun-welcome-pack-toshkent': 'welcome-pack-dlya-it-kompanii-tashkent',
    'lazerli-oyma-va-uf-pechat-nimani-tanlash': 'lazernaya-gravirovka-protiv-uf-pechati-chto-vybrat',
    '8-mart-xodimlarga-sovgalar': 'podarki-na-8-marta-sotrudnicam',
    'originalnye-podarki-na-8-marta-uz': 'originalnye-podarki-na-8-marta',
    'korporativnye-podarki-na-8-marta-v-tashkente-uz': 'korporativnye-podarki-na-8-marta-v-tashkente',
    'chto-podarit-mame-na-8-marta-uz': 'chto-podarit-mame-na-8-marta',
    'chto-podarit-kollege-na-8-marta-uz': 'chto-podarit-kollege-na-8-marta',
    'chto-podarit-rukovoditelyu-na-8-marta-uz': 'chto-podarit-rukovoditelyu-na-8-marta',
    'chto-podarit-devushke-na-8-marta-uz': 'chto-podarit-devushke-na-8-marta',
    'chto-podarit-na-8-marta-devushke-mame-kollege-uz': 'chto-podarit-na-8-marta-devushke-mame-kollege',
    'nedorogie-podarki-na-8-marta-uz': 'nedorogie-podarki-na-8-marta',
    'gravirovka-v-tashkente-na-8-marta-uz': 'gravirovka-v-tashkente-na-8-marta',
    'keys-welcome-pack-povysil-enps-v-it-kompanii-uz': 'keys-welcome-pack-povysil-enps-v-it-kompanii',
    'welcome-pack-hr-uchun-toliq-gid': 'welcome-pack-dlya-sotrudnikov',
    'it-kompaniya-uchun-welcome-pack-chek-listi': 'merch-dlya-it-kompaniy-tashkent',
    'korporativ-sovgalar-toliq-gid-2025-uzbekistan': 'polniy-gid-po-korporativnym-podarkam',
    'xodimlarga-sovga-loyalikni-oshirish': 'podarki-sotrudnikam-hr-gayd',
    'b2b-hamkorlar-uchun-sovgalar-etiket-gid': 'podarki-klientam-partneram-vip',
    'korporativ-sovgalar-zakupshchik-chek-listi': 'chek-list-zakupshchika-podarkov',
    '8-mart-uchun-korporativ-sovgalar-goyalari': 'podarki-na-8-marta-sotrudnicam',
    'rahbar-uchun-8-mart-vip-goya': 'chto-podarit-rukovoditelyu-na-8-marta',
    'biznes-hamkorlar-uchun-vip-sovgalar': 'idei-vip-podarkov',
    'uzbekistonda-biznes-sovga-etiketi': 'delovoy-etiket-biznes-podarki-uzbekistan',
    'vip-sovga-goyalari': 'idei-vip-podarkov',
    'ishbilarmonlik-odobi-biznes-sovgalar-ozbekiston': 'delovoy-etiket-biznes-podarki-uzbekistan',
    // Reverse mappings for pairs where RU->UZ was already present but UZ->RU was missing
    'biznes-sovgalarda-gravyura': 'gravirovka-na-biznes-podarkah',
    'biznes-uchun-eko-sovgalar': 'eko-podarki-dlya-biznesa',
    'keys-welcome-pak-it-kompaniya-toshkent': 'keys-welcome-pak-it-kompaniya-tashkent',
    'korporativ-bayramlar-yillik-rejasi': 'godovoy-plan-korporativnyh-prazdnikov',
    'korporativ-merch-marketing-vositasi': 'korporativniy-merch-kak-instrument-marketinga',
    'korporativ-sovga-buyurtma-jarayoni': 'process-zakaza-korporativnyh-podarkov',
    'korporativ-sovgalar-byudjeti': 'byudzhet-na-korporativnye-podarki',
    'shaxsiylashtirish-yangi-standart-gravyura': 'personalizatsiya-novyy-standart-gravirovka',
    'shoshilinch-korporativ-sovga-buyurtmasi': 'srochniy-zakaz-korporativnyh-podarkov',
    'xodimlar-uchun-sovga-tanlash-chek-list': 'kak-vybrat-podarki-dlya-sotrudnikov',
    // Reverse for new pairs added in this pass
    'keys-brendlangan-sovgalar-it-kompaniya': 'case-study-welcome-pack-enps',
    'b2b-korporativ-sovga-tanlash': 'korporativnye-podarki-b2b-etiket',
    'xodimlar-sadoqati-korporativ-sovgalar': 'podarki-sotrudnikam-loyalnost',
  }
};

export function getMappedAlternateSlug(locale, slug) {
  if (!locale || !slug) return null;
  var byLocale = BLOG_SLUG_MAP[locale];
  if (!byLocale) return null;
  return byLocale[slug] || null;
}
