export const BLOG_SLUG_MAP = {
  ru: {
    'polniy-gid-po-korporativnym-podarkam': 'korporativ-sovgalar-boyicha-toliq-qollanma',
    'kak-vybrat-korporativnyj-podarok': 'korporativ-sovgani-qanday-tanlash',
    'lazernaya-gravirovka-podarkov': 'lazer-gravirovka-sovgalar',
    'podarochnye-nabory-s-logotipom': 'logotipli-sovga-toplami',
    'brendirovanie-suvenirov': 'suvenir-brendlash',
    'chek-list-zakupshchika-podarkov': 'xaridor-chek-listi-b2b',
    'top-idei-podarkov-na-novyj-god': 'yangi-yil-sovga-goyalari',
    'ekonomiya-na-korporativnyh-suvenirax': 'suvenir-byudjetini-tejash',
    'podarki-na-navruz': 'navruz-sovgalari',
    'korporativnye-podarki-s-logotipom-polnyy-gayd': 'korporativ-sovgalar-logotip-bilan-to-liq-qollanma',
    'korporativnye-podarki-s-gravirovkoy-metody': 'korporativ-sovgalar-gravyurasi-usullari',
    'lazernaya-gravirovka-podarkov-tehnologiya': 'lazer-gravyurasi-texnologiyasi',
    'merch-dlya-kompanii-brendirovanie': 'kompaniya-merchi-brendlash',
    'podarki-sotrudnikam-hr-gayd': 'xodimlar-uchun-sovgalar-hr-qollanma',
    'podarki-klientam-partneram-vip': 'mijoz-hamkorlar-uchun-sovgalar-vip',
    'brendirovannye-zazhigalki-i-chasy-s-logotipom': 'logotipli-zajigalka-va-soat',
    'korporativnye-podarochnye-nabory': 'korporativ-sovga-toplamlari',
    'korporativnye-podarki-na-navruz': 'navruz-uchun-korporativ-sovgalar',
    'welcome-pack-novym-sotrudnikam': 'yangi-xodimlar-uchun-welcome-pack',
    'kak-podgotovit-maket-logotipa': 'logotip-maketi-tayyorlash',
    'welcome-pack-dlya-sotrudnikov': 'welcome-pack-yangi-xodimlar',
    'merch-dlya-it-kompaniy-tashkent': 'it-kompaniyalar-uchun-merch-toshkent',
    'podarki-dlya-bankov-i-finteha-tashkent': 'banklar-va-fintex-uchun-sovgalar-toshkent',
    'chasy-s-logotipom-korporativnye-podarki-tashkent': 'logotipli-soat-korporativ-sovgalar-toshkent',
    'podarki-na-korporativnye-sobytiya-tashkent': 'korporativ-tadbirlar-uchun-sovgalar-toshkent',
    'podarki-dlya-horeca-i-restoranov-tashkent': 'horeca-va-restoranlar-uchun-sovgalar-toshkent',
    'idei-vip-podarkov': 'vip-sovga-goyalari',
    'kak-vybrat-podarki-dlya-sotrudnikov': 'xodimlar-uchun-sovga-tanlash-chek-list',
    'gravirovka-na-biznes-podarkah': 'biznes-sovgalarda-gravyura',
    'korporativniy-merch-kak-instrument-marketinga': 'korporativ-merch-marketing-vositasi',
    'byudzhet-na-korporativnye-podarki': 'korporativ-sovgalar-byudjeti',
    'srochniy-zakaz-korporativnyh-podarkov': 'shoshilinch-korporativ-sovga-buyurtmasi',
    'eko-podarki-dlya-biznesa': 'biznes-uchun-eko-sovgalar',
    'keys-brendirovannye-podarki-dlya-it': 'keys-brendlangan-sovgalar-it-kompaniya',
    'loyalnost-sotrudnikov-korporativnye-podarki': 'xodimlar-sadoqati-korporativ-sovgalar',
    'delovoy-etiket-biznes-podarki-uzbekistan': 'ishbilarmonlik-odobi-biznes-sovgalar-ozbekiston',
    'kak-vybrat-korporativnyj-podarok-b2b': 'b2b-korporativ-sovga-tanlash',
    'personalizatsiya-novyy-standart-gravirovka': 'shaxsiylashtirish-yangi-standart-gravyura',
    'process-zakaza-korporativnyh-podarkov': 'korporativ-sovga-buyurtma-jarayoni',
    'keys-welcome-pak-it-kompaniya-tashkent': 'keys-welcome-pak-it-kompaniya-toshkent',
    'godovoy-plan-korporativnyh-prazdnikov': 'korporativ-bayramlar-yillik-rejasi',
    'gastronomicheskie-nabory-na-navruz-tashkent': 'gastronomic-toplamlar-navruzga-toshkent',
    'kak-vybrat-vip-podarok-partneru-uzbekistan': 'vip-hamkor-uchun-sovgani-qanday-tanlash-ozbekiston',
    'welcome-pack-dlya-it-kompanii-tashkent': 'it-kompaniya-uchun-welcome-pack-toshkent',
    'lazernaya-gravirovka-protiv-uf-pechati-chto-vybrat': 'lazerli-oyma-va-uf-pechat-nimani-tanlash',
    'podarki-na-8-marta-sotrudnicam': '8-mart-xodimlarga-sovgalar',
    'originalnye-podarki-na-8-marta': 'originalnye-podarki-na-8-marta-uz',
    'korporativnye-podarki-na-8-marta-v-tashkente': 'korporativnye-podarki-na-8-marta-v-tashkente-uz',
    'chto-podarit-mame-na-8-marta': 'chto-podarit-mame-na-8-marta-uz',
    'chto-podarit-kollege-na-8-marta': 'chto-podarit-kollege-na-8-marta-uz',
    'chto-podarit-rukovoditelyu-na-8-marta': 'chto-podarit-rukovoditelyu-na-8-marta-uz',
    'chto-podarit-devushke-na-8-marta': 'chto-podarit-devushke-na-8-marta-uz',
    'chto-podarit-na-8-marta-devushke-mame-kollege': 'chto-podarit-na-8-marta-devushke-mame-kollege-uz',
    'nedorogie-podarki-na-8-marta': 'nedorogie-podarki-na-8-marta-uz',
    'gravirovka-v-tashkente-na-8-marta': 'gravirovka-v-tashkente-na-8-marta-uz',
  },
  uz: {
    'korporativ-sovgalar-boyicha-toliq-qollanma': 'polniy-gid-po-korporativnym-podarkam',
    'korporativ-sovgani-qanday-tanlash': 'kak-vybrat-korporativnyj-podarok',
    'lazer-gravirovka-sovgalar': 'lazernaya-gravirovka-podarkov',
    'logotipli-sovga-toplami': 'podarochnye-nabory-s-logotipom',
    'suvenir-brendlash': 'brendirovanie-suvenirov',
    'xaridor-chek-listi-b2b': 'chek-list-zakupshchika-podarkov',
    'yangi-yil-sovga-goyalari': 'top-idei-podarkov-na-novyj-god',
    'suvenir-byudjetini-tejash': 'ekonomiya-na-korporativnyh-suvenirax',
    'navruz-sovgalari': 'podarki-na-navruz',
    'korporativ-sovgalar-logotip-bilan-to-liq-qollanma': 'korporativnye-podarki-s-logotipom-polnyy-gayd',
    'korporativ-sovgalar-gravyurasi-usullari': 'korporativnye-podarki-s-gravirovkoy-metody',
    'lazer-gravyurasi-texnologiyasi': 'lazernaya-gravirovka-podarkov-tehnologiya',
    'kompaniya-merchi-brendlash': 'merch-dlya-kompanii-brendirovanie',
    'xodimlar-uchun-sovgalar-hr-qollanma': 'podarki-sotrudnikam-hr-gayd',
    'mijoz-hamkorlar-uchun-sovgalar-vip': 'podarki-klientam-partneram-vip',
    'logotipli-zajigalka-va-soat': 'brendirovannye-zazhigalki-i-chasy-s-logotipom',
    'korporativ-sovga-toplamlari': 'korporativnye-podarochnye-nabory',
    'navruz-uchun-korporativ-sovgalar': 'korporativnye-podarki-na-navruz',
    'yangi-xodimlar-uchun-welcome-pack': 'welcome-pack-novym-sotrudnikam',
    'logotip-maketi-tayyorlash': 'kak-podgotovit-maket-logotipa',
    'welcome-pack-yangi-xodimlar': 'welcome-pack-dlya-sotrudnikov',
    'it-kompaniyalar-uchun-merch-toshkent': 'merch-dlya-it-kompaniy-tashkent',
    'banklar-va-fintex-uchun-sovgalar-toshkent': 'podarki-dlya-bankov-i-finteha-tashkent',
    'logotipli-soat-korporativ-sovgalar-toshkent': 'chasy-s-logotipom-korporativnye-podarki-tashkent',
    'korporativ-tadbirlar-uchun-sovgalar-toshkent': 'podarki-na-korporativnye-sobytiya-tashkent',
    'horeca-va-restoranlar-uchun-sovgalar-toshkent': 'podarki-dlya-horeca-i-restoranov-tashkent',
    'gastronomic-toplamlar-navruzga-toshkent': 'gastronomicheskie-nabory-na-navruz-tashkent',
    'vip-hamkor-uchun-sovgani-qanday-tanlash-ozbekiston': 'kak-vybrat-vip-podarok-partneru-uzbekistan',
    'it-kompaniya-uchun-welcome-pack-toshkent': 'welcome-pack-dlya-it-kompanii-tashkent',
    'lazerli-oyma-va-uf-pechat-nimani-tanlash': 'lazernaya-gravirovka-protiv-uf-pechati-chto-vybrat',
    '8-mart-xodimlarga-sovgalar': 'podarki-na-8-marta-sotrudnicam',
    'originalnye-podarki-na-8-marta-uz': 'originalnye-podarki-na-8-marta',
    'korporativnye-podarki-na-8-marta-v-tashkente-uz': 'korporativnye-podarki-na-8-marta-v-tashkente',
    'chto-podarit-mame-na-8-marta-uz': 'chto-podarit-mame-na-8-marta',
    'chto-podarit-kollege-na-8-marta-uz': 'chto-podarit-kollege-na-8-marta',
    'chto-podarit-rukovoditelyu-na-8-marta-uz': 'chto-podarit-rukovoditelyu-na-8-marta',
    'chto-podarit-devushke-na-8-marta-uz': 'chto-podarit-devushke-na-8-marta',
    'chto-podarit-na-8-marta-devushke-mame-kollege-uz': 'chto-podarit-na-8-marta-devushke-mame-kollege',
    'nedorogie-podarki-na-8-marta-uz': 'nedorogie-podarki-na-8-marta',
    'gravirovka-v-tashkente-na-8-marta-uz': 'gravirovka-v-tashkente-na-8-marta'
  }
};

export function getMappedAlternateSlug(locale, slug) {
  if (!locale || !slug) return null;
  var byLocale = BLOG_SLUG_MAP[locale];
  if (!byLocale) return null;
  return byLocale[slug] || null;
}
